Fail on error and return error code to shell

diff --git a/process_for_month_crontab_finish b/process_for_month_crontab_finish
--- a/process_for_month_crontab_finish
+++ b/process_for_month_crontab_finish
@@ -14,8 +14,22 @@ echo "Finishing processing for month ${month}. Date and time is: "`date` >> ${ou
 echo "-------------------------------------------------------------------" >> ${outputfile}
 echo "Process sirsi records" >> ${outputfile}
 $SCRIPTDIR/process_sirsi_for_month_finish ${testmode} 2>&1 >> ${outputfile}
+res=$?
+if [ ${res} -ne 0 ]; then
+   echo "Error ${res} processing sirsi records, terminating"
+   exit ${res}
+fi
+
 echo "Process tracksys records" >> ${outputfile}
 $SCRIPTDIR/process_tracksys_for_month_finish ${testmode} 2>&1 >> ${outputfile}
+res=$?
+if [ ${res} -ne 0 ]; then
+   echo "Error ${res} processing tracksys records, terminating"
+   exit ${res}
+fi
+
 echo "-------------------------------------------------------------------" >> ${outputfile}
 
-
+#
+# end of file
+#
